[package]
name = "mesos_statistics_publisher"
version = "0.1.0"
authors = ["Cosmin Stroe <cosmin@mailbox.org>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
serde_json = "1.0"
log = "0.4"
simple_logger = "0.5"
futures = "0.1.14"
hyper = "0.11.2"